name: checker
on:
  pull_request:
    branches: [main, test]
  push:
    branches: [main]

jobs:
  checker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: npm install

      - name: start lint
        run: npm run lint
